epochs = 50
batch_size = 8
classes = 67
image_size = 299
image_channels = 3
save_model_dir = "saved"
dataset_dir = "dataset/"
train_dir = dataset_dir + "train"
valid_dir = dataset_dir + "valid"
test_dir = dataset_dir + "test"